
services:
  nginx:
    build: ./requirements/nginx/
    container_name: nginx
    env_file:
      - ./.env
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - wordpress:/var/www/wordpress
    networks:
      - tlonghin-net
    restart: on-failure
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    volumes:
      - mariadb:/var/lib/mysql
    secrets:
      - db_password
      - db_root_password
    env_file:
      - ./.env
    networks:
      - tlonghin-net
    restart: on-failure
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    volumes:
      - wordpress:/var/www/wordpress
    secrets:
      - db_password
      - admin_pass
      - user_pass
    depends_on:
      mariadb:
        condition: service_healthy
    env_file:
      - ./.env
    networks:
      - tlonghin-net
    restart: on-failure
    ports:
      - "9000:9000"
  

volumes:
  wordpress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tlonghin/data/wordpress'
  mariadb:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/home/tlonghin/data/mariadb'

networks:
  tlonghin-net:
    driver: bridge

secrets:
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_password:
    file: ../secrets/db_password.txt
  admin_pass:
    file: ../secrets/admin_pass.txt
  user_pass:
    file: ../secrets/user_pass.txt