FROM debian:buster

RUN apt update -y && \
    apt upgrade -y && \
    apt install mariadb-server -y && \
    mkdir -p /var/run/mysqld && \
    chown -R mysql:mysql /var/run/mysqld && \
    chmod 777 /var/run/mysqld

COPY ./conf/50-server.cnf /etc/mysql/mariadb.conf.d/50-server.cnf
COPY ./tools/installmariadb.sh /usr/local/bin

RUN chmod +x /usr/local/bin/installmariadb.sh

CMD [ "/usr/local/bin/installmariadb.sh" ]

EXPOSE 3306
