FROM debian:buster

RUN apt update -y && \
    apt upgrade -y && \
    apt install -y \
    php-fpm \
    php-mysql \
    php-cli \
    php-xml \
    php-curl \
    php-mbstring \
    php-zip \
    curl \
    vim \
    git \
    unzip \
    wget && \
    mkdir -p /var/www && \
    rm -rf /var/lib/apt/lists/* 

RUN chown -R www-data:www-data /var/www && \
    chmod -R 755 /var/www

COPY ./conf/config.sh /config.sh
RUN chmod +x /config.sh

RUN curl -o /tmp/latest.tar.gz https://wordpress.org/latest.tar.gz && \
    tar -xvzf /tmp/latest.tar.gz -C /var/www/ && \
    mv /var/www/wordpress /var/www/html

EXPOSE 9000

CMD /config.sh && php-fpm7.4 -F
